lsi: false
safe: true
source: https://github.com/fredericvergnaud/manuel-scraping
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
